version: '3.9'
services:
    node-api:
        image: ghcr.io/zyrass/cicd-projet-docker/node-api:latest
    frontend:
        image: ghcr.io/zyrass/cicd-projet-docker/frontend:latest
    cypress:
        image: cypress/included
        working_dir: /e2e
        volumes:
            - ./frontend:/e2e
        entrypoint: cypress run --config baseUrl=http://frontend --headless --browser chrome
        depends_on:
            - frontend
            - node-api
