name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Github Container Registery
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Convert github.actor in lowercase
              run: echo "ACTOR_LOWER=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

            - name: Build and push Docker image
              run: |
                  docker build -t ghcr.io/$ACTOR_LOWER/frontend .
                  docker push ghcr.io/$ACTOR_LOWER/frontend
                  docker build -t ghcr.io/$ACTOR_LOWER/node-api .
                  docker push ghcr.io/$ACTOR_LOWER/node-api
