name: CI

on:
    push:
        branches:
            - main

jobs:
    build-frontend-and-node-api:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                includes:
                    - context_name: ./frontend
                      image_name: ghcr.io/${{ github.actor }}/${{ github.repository }}/frontend
                    - context_name: ./node-api
                      image_name: ghcr.io/${{ github.actor }}/${{ github.repository }}/node-api
        permissions:
            packages: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: ${{ matrix.context_name }}
                  push: true
                  tags: ${{ matrix.image_name }}:latest
                  cache-from: type=gha # Cache de github actions
                  cache-to: type=gha,mode=max

        # build:
        #     runs-on: ubuntu-latest

        #     steps:
        #         - name: Checkout code
        #           uses: actions/checkout@v4

        #         - name: Login to Github Container Registery
        #           run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        #         - name: Convert github.actor in lowercase
        #           run: echo "ACTOR_LOWER=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

        #         - name: Build and push Docker image
        #           run: |
        #               docker build -t ghcr.io/$ACTOR_LOWER/frontend .
        #               docker push ghcr.io/$ACTOR_LOWER/frontend
        #               docker build -t ghcr.io/$ACTOR_LOWER/node-api .
        #               docker push ghcr.io/$ACTOR_LOWER/node-api
